import { User, Event, Club, Chat, Message } from './types'

// Mock Users
export const mockUsers: Record<string, User> = {
  'user1': {
    id: 'user1',
    name: 'John Doe',
    email: 'john@example.com',
    avatar: '👨‍🦰',
    bio: 'Basketball enthusiast',
    sports: ['basketball', 'tennis'],
    location: 'Hong Kong',
    joinedDate: '2024-01-15',
  },
  'user2': {
    id: 'user2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    avatar: '👩‍🦱',
    bio: 'Soccer player',
    sports: ['soccer', 'volleyball'],
    location: 'Hong Kong',
    joinedDate: '2024-02-20',
  },
  'user3': {
    id: 'user3',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    avatar: '👨‍💼',
    bio: 'Tennis coach',
    sports: ['tennis', 'badminton'],
    location: 'Hong Kong',
    joinedDate: '2024-03-10',
  },
  'user4': {
    id: 'user4',
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    avatar: '👩‍🦳',
    bio: 'Volleyball player',
    sports: ['volleyball', 'soccer'],
    location: 'Hong Kong',
    joinedDate: '2024-03-15',
  },
  'demo': {
    id: 'demo',
    name: 'Demo User',
    email: 'demo@example.com',
    avatar: '👤',
    bio: 'Demo user for testing',
    sports: ['basketball', 'tennis', 'soccer'],
    location: 'Hong Kong',
    joinedDate: '2024-04-01',
  },
}

// Mock Events
export const mockEvents: Event[] = [
  {
    id: 'event1',
    title: 'Basketball Game at Victoria Park',
    description: 'Friendly basketball game for intermediate players. All skill levels welcome!',
    sportType: 'basketball',
    date: '2026-04-06',
    time: '18:00',
    location: 'Victoria Park, Causeway Bay, Hong Kong',
    latitude: 22.2797,
    longitude: 114.1839,
    skillLevel: 'intermediate',
    maxParticipants: 10,
    currentParticipants: 7,
    organizerId: 'user1',
    organizer: mockUsers['user1'],
    status: 'upcoming',
    participants: ['user1', 'user2', 'user3', 'user4', 'user5', 'user6', 'demo'],
    waitlist: ['user7', 'user8'],
    coHosts: ['user2'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event2',
    title: 'Tennis Match at Hong Kong Park',
    description: 'Competitive tennis match for advanced players',
    sportType: 'tennis',
    date: '2026-04-06',
    time: '09:00',
    location: 'Hong Kong Park, Central, Hong Kong',
    latitude: 22.2738,
    longitude: 114.1740,
    skillLevel: 'advanced',
    maxParticipants: 4,
    currentParticipants: 3,
    organizerId: 'user3',
    organizer: mockUsers['user3'],
    status: 'upcoming',
    participants: ['user3', 'user1', 'user4'],
    waitlist: ['user2', 'demo', 'user5'],
    coHosts: ['user1'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event3',
    title: 'Volleyball Tournament at Repulse Bay',
    description: 'Beach volleyball tournament with multiple teams',
    sportType: 'volleyball',
    date: '2026-04-15',
    time: '14:00',
    location: 'Repulse Bay Beach, Hong Kong',
    latitude: 22.2858,
    longitude: 114.1819,
    skillLevel: 'intermediate',
    maxParticipants: 12,
    currentParticipants: 9,
    organizerId: 'user4',
    organizer: mockUsers['user4'],
    status: 'upcoming',
    participants: ['user4', 'user2', 'user1', 'user3', 'user5', 'user6', 'user7', 'user8', 'demo'],
    waitlist: ['user9', 'user10'],
    coHosts: ['user2'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event4',
    title: 'Soccer Practice at Kowloon Park',
    description: 'Regular soccer practice session for all levels',
    sportType: 'soccer',
    date: '2026-04-07',
    time: '19:30',
    location: 'Kowloon Park, Tsim Sha Tsui, Hong Kong',
    latitude: 22.2980,
    longitude: 114.1738,
    skillLevel: 'beginner',
    maxParticipants: 15,
    currentParticipants: 10,
    organizerId: 'user2',
    organizer: mockUsers['user2'],
    status: 'upcoming',
    participants: ['user2', 'user1', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10'],
    waitlist: ['user11', 'user12'],
    coHosts: ['user3'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event5',
    title: 'Badminton Doubles at Southorn Stadium',
    description: 'Friendly badminton doubles tournament',
    sportType: 'badminton',
    date: '2026-04-16',
    time: '10:00',
    location: 'Southorn Stadium, Wan Chai, Hong Kong',
    latitude: 22.2766,
    longitude: 114.1790,
    skillLevel: 'intermediate',
    maxParticipants: 8,
    currentParticipants: 6,
    organizerId: 'user1',
    organizer: mockUsers['user1'],
    status: 'upcoming',
    participants: ['user1', 'user3', 'user4', 'user2', 'user5', 'user6'],
    waitlist: ['user7', 'user8'],
    coHosts: ['user3'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event6',
    title: 'Morning Running Group at Victoria Park',
    description: 'Easy paced morning run for all fitness levels',
    sportType: 'running',
    date: '2026-04-06',
    time: '06:30',
    location: 'Victoria Park, Causeway Bay, Hong Kong',
    latitude: 22.2797,
    longitude: 114.1839,
    skillLevel: 'beginner',
    maxParticipants: 20,
    currentParticipants: 12,
    organizerId: 'user2',
    organizer: mockUsers['user2'],
    status: 'upcoming',
    participants: ['user2', 'user1', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12'],
    waitlist: ['user13', 'user14'],
    coHosts: ['user3'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event7',
    title: 'Cricket Practice at Kowloon Cricket Club',
    description: 'Cricket practice and coaching session',
    sportType: 'cricket',
    date: '2026-04-10',
    time: '15:00',
    location: 'Kowloon Cricket Club, Kowloon, Hong Kong',
    latitude: 22.3150,
    longitude: 114.1700,
    skillLevel: 'intermediate',
    maxParticipants: 11,
    currentParticipants: 9,
    organizerId: 'user3',
    organizer: mockUsers['user3'],
    status: 'upcoming',
    participants: ['user3', 'user1', 'user2', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9'],
    waitlist: [],
    coHosts: ['user2'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event8',
    title: 'Yoga Session at Central Park',
    description: 'Relaxing yoga session for all levels',
    sportType: 'yoga',
    date: '2026-04-07',
    time: '07:00',
    location: 'Central Park, Central, Hong Kong',
    latitude: 22.2738,
    longitude: 114.1740,
    skillLevel: 'beginner',
    maxParticipants: 25,
    currentParticipants: 18,
    organizerId: 'user4',
    organizer: mockUsers['user4'],
    status: 'upcoming',
    participants: ['user4', 'user1', 'user2', 'user3', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12', 'user13', 'user14', 'user15', 'user16', 'user17', 'user18'],
    waitlist: [],
    coHosts: [],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event9',
    title: 'Cycling Tour Around Hong Kong Island',
    description: 'Scenic cycling tour around Hong Kong Island',
    sportType: 'cycling',
    date: '2026-04-13',
    time: '08:00',
    location: 'Stanley, Hong Kong Island, Hong Kong',
    latitude: 22.2129,
    longitude: 114.2089,
    skillLevel: 'intermediate',
    maxParticipants: 15,
    currentParticipants: 10,
    organizerId: 'user1',
    organizer: mockUsers['user1'],
    status: 'upcoming',
    participants: ['user1', 'user2', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10'],
    waitlist: [],
    coHosts: ['user4'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event10',
    title: 'Swimming Training at Victoria Park Pool',
    description: 'Swimming training and coaching',
    sportType: 'swimming',
    date: '2026-04-03',
    time: '17:00',
    location: 'Victoria Park Swimming Pool, Causeway Bay, Hong Kong',
    latitude: 22.2797,
    longitude: 114.1839,
    skillLevel: 'intermediate',
    maxParticipants: 20,
    currentParticipants: 14,
    organizerId: 'user2',
    organizer: mockUsers['user2'],
    status: 'upcoming',
    participants: ['user2', 'user1', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12', 'user13', 'user14'],
    waitlist: [],
    coHosts: [],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event11',
    title: 'Pickleball Tournament at Southorn Stadium',
    description: 'Fun pickleball tournament with prizes for winners',
    sportType: 'pickleball',
    date: '2026-04-12',
    time: '16:00',
    location: 'Southorn Stadium, Causeway Bay, Hong Kong',
    latitude: 22.2797,
    longitude: 114.1839,
    skillLevel: 'beginner',
    maxParticipants: 16,
    currentParticipants: 12,
    organizerId: 'user1',
    organizer: mockUsers['user1'],
    status: 'upcoming',
    participants: ['user1', 'user2', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12'],
    waitlist: ['user13', 'user14'],
    coHosts: ['user3'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event12',
    title: 'Fitness & CrossFit Training',
    description: 'High intensity fitness training session with certified coaches',
    sportType: 'other',
    date: '2026-04-04',
    time: '06:30',
    location: 'Central Fitness Center, Central, Hong Kong',
    latitude: 22.2738,
    longitude: 114.1740,
    skillLevel: 'intermediate',
    maxParticipants: 20,
    currentParticipants: 15,
    organizerId: 'user3',
    organizer: mockUsers['user3'],
    status: 'upcoming',
    participants: ['user3', 'user1', 'user2', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12', 'user13', 'user14', 'user15'],
    waitlist: [],
    coHosts: ['user1'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event13',
    title: 'Hiking Adventure at Lion Rock',
    description: 'Scenic hiking adventure with breathtaking views',
    sportType: 'other',
    date: '2026-04-16',
    time: '07:30',
    location: 'Lion Rock, Kowloon, Hong Kong',
    latitude: 22.3212,
    longitude: 114.1880,
    skillLevel: 'advanced',
    maxParticipants: 25,
    currentParticipants: 18,
    organizerId: 'user4',
    organizer: mockUsers['user4'],
    status: 'upcoming',
    participants: ['user4', 'user1', 'user2', 'user3', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12', 'user13', 'user14', 'user15', 'user16', 'user17', 'user18'],
    waitlist: [],
    coHosts: ['user2'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event14',
    title: 'Table Tennis Championship',
    description: 'Competitive table tennis championship with multiple rounds',
    sportType: 'other',
    date: '2026-04-06',
    time: '19:00',
    location: 'Hong Kong Table Tennis Center, Kowloon, Hong Kong',
    latitude: 22.2980,
    longitude: 114.1738,
    skillLevel: 'advanced',
    maxParticipants: 32,
    currentParticipants: 24,
    organizerId: 'user2',
    organizer: mockUsers['user2'],
    status: 'upcoming',
    participants: ['user2', 'user1', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12', 'user13', 'user14', 'user15', 'user16', 'user17', 'user18', 'user19', 'user20', 'user21', 'user22', 'user23', 'user24'],
    waitlist: [],
    coHosts: ['user3'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event15',
    title: 'Martial Arts Training Session',
    description: 'Karate and martial arts training for all belt levels',
    sportType: 'other',
    date: '2026-04-13',
    time: '18:00',
    location: 'Hong Kong Martial Arts Academy, Tsim Sha Tsui, Hong Kong',
    latitude: 22.2980,
    longitude: 114.1738,
    skillLevel: 'intermediate',
    maxParticipants: 20,
    currentParticipants: 16,
    organizerId: 'user1',
    organizer: mockUsers['user1'],
    status: 'upcoming',
    participants: ['user1', 'user2', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12', 'user13', 'user14', 'user15', 'user16'],
    waitlist: [],
    coHosts: ['user4'],
    reservedGuests: [],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
]

// Mock Clubs
export const mockClubs: Club[] = [
  {
    id: 'club1',
    name: 'SF Basketball Club',
    description: 'A vibrant community for basketball enthusiasts. We organize weekly games, training sessions, and tournaments. All skill levels welcome! Join us for competitive matches and friendly pickup games.',
    sport: 'basketball',
    creatorId: 'user1',
    creator: mockUsers['user1'],
    members: ['user1', 'user2', 'user3', 'user4'],
    admins: ['user1'],
    organizers: ['user1'],
    groupChatId: 'chat_club1',
    isPrivate: false,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-01',
    events: [mockEvents[0], mockEvents[10]],
    membershipRequests: [],
  },
  {
    id: 'club2',
    name: 'Tennis Lovers',
    description: 'Passionate tennis community for players of all skill levels. We organize coaching sessions, friendly matches, and competitive tournaments. Professional coaches available for training.',
    sport: 'tennis',
    creatorId: 'user3',
    creator: mockUsers['user3'],
    members: ['user3', 'user1', 'user4'],
    admins: ['user3'],
    organizers: ['user3'],
    groupChatId: 'chat_club2',
    isPrivate: false,
    createdAt: '2024-03-05',
    updatedAt: '2024-03-05',
    events: [mockEvents[1]],  // Tennis Match
    membershipRequests: [],
  },
  {
    id: 'club3',
    name: 'Volleyball Community',
    description: 'Join our dynamic volleyball community! We play both beach and indoor volleyball. Regular training sessions, friendly matches, and competitive tournaments throughout the year.',
    sport: 'volleyball',
    creatorId: 'user4',
    creator: mockUsers['user4'],
    members: ['user4', 'user2', 'user1'],
    admins: ['user4'],
    organizers: ['user4'],
    groupChatId: 'chat_club3',
    isPrivate: false,
    createdAt: '2024-03-10',
    updatedAt: '2024-03-10',
    events: [mockEvents[2]],  // Volleyball Tournament
    membershipRequests: [],
  },
  {
    id: 'club4',
    name: 'Soccer Enthusiasts',
    description: 'Passionate soccer community with regular matches, training sessions, and tournaments. We welcome players of all ages and skill levels. Professional coaching available.',
    sport: 'soccer',
    creatorId: 'user2',
    creator: mockUsers['user2'],
    members: ['user2', 'user1', 'user3', 'user4'],
    admins: ['user2'],
    organizers: ['user2'],
    groupChatId: 'chat_club4',
    isPrivate: false,
    createdAt: '2024-03-15',
    updatedAt: '2024-03-15',
    events: [mockEvents[3]],  // Soccer Practice
    membershipRequests: [],
  },
  {
    id: 'club5',
    name: 'Badminton Masters',
    description: 'Elite badminton club for experienced and advanced players. We organize competitive tournaments, training camps, and friendly matches. Membership requires badminton experience.',
    sport: 'badminton',
    creatorId: 'user1',
    creator: mockUsers['user1'],
    members: ['user1', 'user3', 'user4'],
    admins: ['user1'],
    organizers: ['user1', 'user3'],
    groupChatId: 'chat_club5',
    isPrivate: false,
    createdAt: '2024-03-20',
    updatedAt: '2024-03-20',
    events: [mockEvents[4]],  // Badminton Doubles
    membershipRequests: [],
  },
  {
    id: 'club6',
    name: 'Running Enthusiasts',
    description: 'Active running community with daily jogs, marathon training, and running events. We organize group runs at various distances and speeds for all fitness levels.',
    sport: 'running',
    creatorId: 'user2',
    creator: mockUsers['user2'],
    members: ['user2', 'user1', 'user3', 'user4'],
    admins: ['user2'],
    organizers: ['user2', 'user3'],
    groupChatId: 'chat_club6',
    isPrivate: false,
    createdAt: '2024-03-22',
    updatedAt: '2024-03-22',
    events: [mockEvents[5]],  // Morning Running
    membershipRequests: [],
  },
  {
    id: 'club7',
    name: 'Cricket Club',
    description: 'Vibrant cricket community with regular matches, training sessions, and tournaments. We welcome players of all ages and skill levels. Professional coaching available.',
    sport: 'cricket',
    creatorId: 'user3',
    creator: mockUsers['user3'],
    members: ['user3', 'user1', 'user2', 'user4'],
    admins: ['user3'],
    organizers: ['user3', 'user2'],
    groupChatId: 'chat_club7',
    isPrivate: false,
    createdAt: '2024-03-25',
    updatedAt: '2024-03-25',
    events: [mockEvents[6]],  // Cricket Practice
    membershipRequests: [],
  },
  {
    id: 'club8',
    name: 'Yoga & Wellness',
    description: 'Holistic wellness community offering yoga classes, meditation sessions, and wellness workshops. Perfect for relaxation, fitness, and mental health. All levels welcome.',
    sport: 'yoga',
    creatorId: 'user4',
    creator: mockUsers['user4'],
    members: ['user4', 'user1', 'user2', 'user3'],
    admins: ['user4'],
    organizers: ['user4'],
    groupChatId: 'chat_club8',
    isPrivate: false,
    createdAt: '2024-03-28',
    updatedAt: '2024-03-28',
    events: [mockEvents[7]],  // Yoga Session
    membershipRequests: [],
  },
  {
    id: 'club9',
    name: 'Cycling Adventures',
    description: 'Adventure cycling community exploring scenic routes around Hong Kong. We organize group rides, mountain biking tours, and cycling events. All skill levels welcome.',
    sport: 'cycling',
    creatorId: 'user1',
    creator: mockUsers['user1'],
    members: ['user1', 'user2', 'user3', 'user4'],
    admins: ['user1'],
    organizers: ['user1', 'user4'],
    groupChatId: 'chat_club9',
    isPrivate: false,
    createdAt: '2024-03-30',
    updatedAt: '2024-03-30',
    events: [mockEvents[8]],  // Cycling Tour
    membershipRequests: [],
  },
  {
    id: 'club10',
    name: 'Swimming Club',
    description: 'Comprehensive swimming club offering training, coaching, and water sports activities. We organize swimming competitions, training camps, and recreational sessions.',
    sport: 'swimming',
    creatorId: 'user2',
    creator: mockUsers['user2'],
    members: ['user2', 'user1', 'user3', 'user4'],
    admins: ['user2'],
    organizers: ['user2'],
    groupChatId: 'chat_club10',
    isPrivate: false,
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
    events: [mockEvents[9]],  // Swimming Training
    membershipRequests: [],
  },
  {
    id: 'club11',
    name: 'Pickleball Players',
    description: 'Fun and social pickleball community! Perfect for beginners and experienced players. We organize casual games, tournaments, and social events. Great way to make friends!',
    sport: 'pickleball',
    creatorId: 'user1',
    creator: mockUsers['user1'],
    members: ['user1', 'user2', 'user3'],
    admins: ['user1'],
    organizers: ['user1'],
    groupChatId: 'chat_club11',
    isPrivate: false,
    createdAt: '2024-04-02',
    updatedAt: '2024-04-02',
    events: [mockEvents[10]],
    membershipRequests: [],
  },
  {
    id: 'club12',
    name: 'Fitness & CrossFit',
    description: 'High-intensity fitness and CrossFit club with certified coaches. We offer personalized training, group classes, and fitness competitions. Transform your fitness journey!',
    sport: 'other',
    creatorId: 'user3',
    creator: mockUsers['user3'],
    members: ['user3', 'user1', 'user4', 'user2'],
    admins: ['user3'],
    organizers: ['user3', 'user1'],
    groupChatId: 'chat_club12',
    isPrivate: false,
    createdAt: '2024-04-03',
    updatedAt: '2024-04-03',
    events: [mockEvents[11]],
    membershipRequests: [],
  },
  {
    id: 'club13',
    name: 'Hiking & Trekking',
    description: 'Adventure hiking and trekking club exploring scenic trails and mountains. We organize guided hikes, camping trips, and outdoor adventures for all fitness levels.',
    sport: 'other',
    creatorId: 'user4',
    creator: mockUsers['user4'],
    members: ['user4', 'user1', 'user2', 'user3'],
    admins: ['user4'],
    organizers: ['user4', 'user2'],
    groupChatId: 'chat_club13',
    isPrivate: false,
    createdAt: '2024-04-04',
    updatedAt: '2024-04-04',
    events: [mockEvents[12]],
    membershipRequests: [],
  },
  {
    id: 'club14',
    name: 'Table Tennis Club',
    description: 'Competitive table tennis club with regular matches, training sessions, and tournaments. Professional coaching available. All skill levels welcome to join!',
    sport: 'other',
    creatorId: 'user2',
    creator: mockUsers['user2'],
    members: ['user2', 'user1', 'user3', 'user4'],
    admins: ['user2'],
    organizers: ['user2', 'user3'],
    groupChatId: 'chat_club14',
    isPrivate: false,
    createdAt: '2024-04-05',
    updatedAt: '2024-04-05',
    events: [mockEvents[13]],
    membershipRequests: [],
  },
  {
    id: 'club15',
    name: 'Martial Arts Dojo',
    description: 'Professional martial arts training center offering Karate, Taekwondo, and other disciplines. Expert instructors, belt progression programs, and competitive opportunities available.',
    sport: 'other',
    creatorId: 'user1',
    creator: mockUsers['user1'],
    members: ['user1', 'user3', 'user4'],
    admins: ['user1'],
    organizers: ['user1'],
    groupChatId: 'chat_club15',
    isPrivate: false,
    createdAt: '2024-04-06',
    updatedAt: '2024-04-06',
    events: [mockEvents[14]],
    membershipRequests: [],
  },
]

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: 'msg1',
    chatId: 'chat1',
    senderId: 'user1',
    sender: mockUsers['user1'],
    content: 'Hey! Are you coming to the basketball game tomorrow?',
    createdAt: '2024-04-10T10:00:00Z',
  },
  {
    id: 'msg2',
    chatId: 'chat1',
    senderId: 'user2',
    sender: mockUsers['user2'],
    content: 'Yes! I\'ll be there. What time should I arrive?',
    createdAt: '2024-04-10T10:05:00Z',
  },
  {
    id: 'msg3',
    chatId: 'chat1',
    senderId: 'user1',
    sender: mockUsers['user1'],
    content: 'Around 5 PM would be great!',
    createdAt: '2024-04-10T10:10:00Z',
  },
]

// Mock Chats
export const mockChats: Chat[] = [
  {
    id: 'chat1',
    type: 'direct',
    participants: ['user1', 'user2'],
    messages: mockMessages,
    createdAt: '2024-04-01',
    updatedAt: '2024-04-10',
  },
  {
    id: 'chat2',
    type: 'group',
    name: 'Basketball Team',
    participants: ['user1', 'user2', 'user3', 'user4'],
    messages: [
      {
        id: 'msg4',
        chatId: 'chat2',
        senderId: 'user1',
        sender: mockUsers['user1'],
        content: 'Team meeting tomorrow at 5 PM!',
        createdAt: '2024-04-10T11:00:00Z',
      },
    ],
    createdAt: '2024-04-05',
    updatedAt: '2024-04-10',
  },
]

export default {
  mockUsers,
  mockEvents,
  mockClubs,
  mockMessages,
  mockChats,
}
