import { User, Event, Club, Chat, Message } from './types'

// Mock Users
export const mockUsers: Record<string, User> = {
  'user1': {
    id: 'user1',
    name: 'John Doe',
    email: 'john@example.com',
    avatar: '👨‍🦰',
    bio: 'Basketball enthusiast',
    sports: ['basketball', 'tennis'],
    location: 'San Francisco, CA',
    joinedDate: '2024-01-15',
  },
  'user2': {
    id: 'user2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    avatar: '👩‍🦱',
    bio: 'Soccer player',
    sports: ['soccer', 'volleyball'],
    location: 'San Francisco, CA',
    joinedDate: '2024-02-20',
  },
  'user3': {
    id: 'user3',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    avatar: '👨‍💼',
    bio: 'Tennis coach',
    sports: ['tennis', 'badminton'],
    location: 'San Francisco, CA',
    joinedDate: '2024-03-10',
  },
  'user4': {
    id: 'user4',
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    avatar: '👩‍🦳',
    bio: 'Volleyball player',
    sports: ['volleyball', 'soccer'],
    location: 'San Francisco, CA',
    joinedDate: '2024-03-15',
  },
}

// Mock Events
export const mockEvents: Event[] = [
  {
    id: 'event1',
    title: 'Basketball Game at Golden Gate Park',
    description: 'Friendly basketball game for intermediate players. All skill levels welcome!',
    sportType: 'basketball',
    date: '2024-04-15',
    time: '18:00',
    location: 'Golden Gate Park, San Francisco',
    latitude: 37.7694,
    longitude: -122.4862,
    skillLevel: 'intermediate',
    maxParticipants: 10,
    currentParticipants: 6,
    organizerId: 'user1',
    organizer: mockUsers['user1'],
    status: 'upcoming',
    participants: ['user1', 'user2', 'user3', 'user4', 'user5', 'user6'],
    waitlist: [],
    coHosts: ['user2'],
    reservedGuests: [
      { name: 'Alex', id: 'guest1', status: 'approved', reservedBy: 'user1' },
    ],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event2',
    title: 'Tennis Match at Mission Bay',
    description: 'Looking for tennis partners for doubles match',
    sportType: 'tennis',
    date: '2024-04-16',
    time: '10:00',
    location: 'Mission Bay, San Francisco',
    latitude: 37.7597,
    longitude: -122.3929,
    skillLevel: 'advanced',
    maxParticipants: 4,
    currentParticipants: 3,
    organizerId: 'user3',
    organizer: mockUsers['user3'],
    status: 'upcoming',
    participants: ['user3', 'user1', 'user4'],
    waitlist: ['user2'],
    coHosts: [],
    createdAt: '2024-04-02',
    updatedAt: '2024-04-02',
  },
  {
    id: 'event3',
    title: 'Volleyball Tournament',
    description: 'Beach volleyball tournament at Ocean Beach',
    sportType: 'volleyball',
    date: '2024-04-17',
    time: '14:00',
    location: 'Ocean Beach, San Francisco',
    latitude: 37.7505,
    longitude: -122.5107,
    skillLevel: 'beginner',
    maxParticipants: 12,
    currentParticipants: 8,
    organizerId: 'user4',
    organizer: mockUsers['user4'],
    status: 'upcoming',
    participants: ['user4', 'user2', 'user3', 'user1', 'user5', 'user6', 'user7', 'user8'],
    waitlist: [],
    coHosts: ['user2'],
    createdAt: '2024-04-03',
    updatedAt: '2024-04-03',
  },
  {
    id: 'event4',
    title: 'Soccer Practice',
    description: 'Weekly soccer practice for all skill levels',
    sportType: 'soccer',
    date: '2024-04-18',
    time: '19:00',
    location: 'Dolores Park, San Francisco',
    latitude: 37.7599,
    longitude: -122.4148,
    skillLevel: 'intermediate',
    maxParticipants: 15,
    currentParticipants: 10,
    organizerId: 'user2',
    organizer: mockUsers['user2'],
    status: 'upcoming',
    participants: ['user2', 'user1', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10'],
    waitlist: ['user11'],
    coHosts: [],
    createdAt: '2024-04-04',
    updatedAt: '2024-04-04',
  },
]

// Mock Clubs
export const mockClubs: Club[] = [
  {
    id: 'club1',
    name: 'SF Basketball Club',
    description: 'A community for basketball enthusiasts in San Francisco',
    sport: 'basketball',
    creatorId: 'user1',
    creator: mockUsers['user1'],
    members: ['user1', 'user2', 'user3', 'user4'],
    admins: ['user1'],
    isPrivate: false,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-01',
    events: [mockEvents[0]],
  },
  {
    id: 'club2',
    name: 'Tennis Lovers',
    description: 'For tennis players of all skill levels',
    sport: 'tennis',
    creatorId: 'user3',
    creator: mockUsers['user3'],
    members: ['user3', 'user1', 'user4'],
    admins: ['user3'],
    isPrivate: false,
    createdAt: '2024-03-05',
    updatedAt: '2024-03-05',
    events: [mockEvents[1]],
  },
  {
    id: 'club3',
    name: 'Volleyball Community',
    description: 'Beach and indoor volleyball players',
    sport: 'volleyball',
    creatorId: 'user4',
    creator: mockUsers['user4'],
    members: ['user4', 'user2', 'user1'],
    admins: ['user4'],
    isPrivate: false,
    createdAt: '2024-03-10',
    updatedAt: '2024-03-10',
    events: [mockEvents[2]],
  },
  {
    id: 'club4',
    name: 'Soccer Enthusiasts',
    description: 'Join us for soccer games and training',
    sport: 'soccer',
    creatorId: 'user2',
    creator: mockUsers['user2'],
    members: ['user2', 'user1', 'user3', 'user4'],
    admins: ['user2'],
    isPrivate: false,
    createdAt: '2024-03-15',
    updatedAt: '2024-03-15',
    events: [mockEvents[3]],
  },
]

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: 'msg1',
    chatId: 'chat1',
    senderId: 'user1',
    sender: mockUsers['user1'],
    content: 'Hey! Are you coming to the basketball game tomorrow?',
    createdAt: '2024-04-10T10:00:00Z',
  },
  {
    id: 'msg2',
    chatId: 'chat1',
    senderId: 'user2',
    sender: mockUsers['user2'],
    content: 'Yes! I\'ll be there. What time should I arrive?',
    createdAt: '2024-04-10T10:05:00Z',
  },
  {
    id: 'msg3',
    chatId: 'chat1',
    senderId: 'user1',
    sender: mockUsers['user1'],
    content: 'Around 5 PM would be great!',
    createdAt: '2024-04-10T10:10:00Z',
  },
]

// Mock Chats
export const mockChats: Chat[] = [
  {
    id: 'chat1',
    type: 'direct',
    participants: ['user1', 'user2'],
    messages: mockMessages,
    createdAt: '2024-04-01',
    updatedAt: '2024-04-10',
  },
  {
    id: 'chat2',
    type: 'group',
    name: 'Basketball Team',
    participants: ['user1', 'user2', 'user3', 'user4'],
    messages: [
      {
        id: 'msg4',
        chatId: 'chat2',
        senderId: 'user1',
        sender: mockUsers['user1'],
        content: 'Team meeting tomorrow at 5 PM!',
        createdAt: '2024-04-10T11:00:00Z',
      },
    ],
    createdAt: '2024-04-05',
    updatedAt: '2024-04-10',
  },
]

export default {
  mockUsers,
  mockEvents,
  mockClubs,
  mockMessages,
  mockChats,
}
