import { User, Event, Club, Chat, Message } from './types'

// Mock Users
export const mockUsers: Record<string, User> = {
  'user1': {
    id: 'user1',
    name: 'John Doe',
    email: 'john@example.com',
    avatar: '👨‍🦰',
    bio: 'Basketball enthusiast',
    sports: ['basketball', 'tennis'],
    location: 'Hong Kong',
    joinedDate: '2024-01-15',
  },
  'user2': {
    id: 'user2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    avatar: '👩‍🦱',
    bio: 'Soccer player',
    sports: ['soccer', 'volleyball'],
    location: 'Hong Kong',
    joinedDate: '2024-02-20',
  },
  'user3': {
    id: 'user3',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    avatar: '👨‍💼',
    bio: 'Tennis coach',
    sports: ['tennis', 'badminton'],
    location: 'Hong Kong',
    joinedDate: '2024-03-10',
  },
  'user4': {
    id: 'user4',
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    avatar: '👩‍🦳',
    bio: 'Volleyball player',
    sports: ['volleyball', 'soccer'],
    location: 'Hong Kong',
    joinedDate: '2024-03-15',
  },
}

// Mock Events
export const mockEvents: Event[] = [
  {
    id: 'event1',
    title: 'Basketball Game at Victoria Park',
    description: 'Friendly basketball game for intermediate players. All skill levels welcome!',
    sportType: 'basketball',
    date: '2026-03-31',
    time: '18:00',
    location: 'Victoria Park, Causeway Bay, Hong Kong',
    latitude: 22.2797,
    longitude: 114.1839,
    skillLevel: 'intermediate',
    maxParticipants: 10,
    currentParticipants: 6,
    organizerId: 'user1',
    organizer: mockUsers['user1'],
    status: 'upcoming',
    participants: ['user1', 'user2', 'user3', 'user4', 'user5', 'user6'],
    waitlist: [],
    coHosts: ['user2'],
    reservedGuests: [
      { name: 'Alex', id: 'guest1', status: 'approved', reservedBy: 'user1' },
    ],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: 'event2',
    title: 'Tennis Match at Hong Kong Tennis Centre',
    description: 'Looking for tennis partners for doubles match',
    sportType: 'tennis',
    date: '2026-04-01',
    time: '10:00',
    location: 'Hong Kong Tennis Centre, Wong Chuk Hang, Hong Kong',
    latitude: 22.2854,
    longitude: 114.1726,
    skillLevel: 'advanced',
    maxParticipants: 4,
    currentParticipants: 3,
    organizerId: 'user3',
    organizer: mockUsers['user3'],
    status: 'upcoming',
    participants: ['user3', 'user1', 'user4'],
    waitlist: ['user2'],
    coHosts: [],
    createdAt: '2024-04-02',
    updatedAt: '2024-04-02',
  },
  {
    id: 'event3',
    title: 'Volleyball Tournament',
    description: 'Beach volleyball tournament at Repulse Bay',
    sportType: 'volleyball',
    date: '2026-04-02',
    time: '14:00',
    location: 'Repulse Bay Beach, Hong Kong',
    latitude: 22.2863,
    longitude: 114.1766,
    skillLevel: 'beginner',
    maxParticipants: 12,
    currentParticipants: 8,
    organizerId: 'user4',
    organizer: mockUsers['user4'],
    status: 'upcoming',
    participants: ['user4', 'user2', 'user3', 'user1', 'user5', 'user6', 'user7', 'user8'],
    waitlist: [],
    coHosts: ['user2'],
    createdAt: '2024-04-03',
    updatedAt: '2024-04-03',
  },
  {
    id: 'event4',
    title: 'Soccer Practice',
    description: 'Weekly soccer practice for all skill levels',
    sportType: 'soccer',
    date: '2026-04-03',
    time: '19:00',
    location: 'Hong Kong Football Club, Happy Valley, Hong Kong',
    latitude: 22.2750,
    longitude: 114.1847,
    skillLevel: 'intermediate',
    maxParticipants: 15,
    currentParticipants: 10,
    organizerId: 'user2',
    organizer: mockUsers['user2'],
    status: 'upcoming',
    participants: ['user2', 'user1', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10'],
    waitlist: ['user11'],
    coHosts: [],
    createdAt: '2024-04-04',
    updatedAt: '2024-04-04',
  },
  {
    id: 'event5',
    title: 'Badminton Doubles',
    description: 'Casual badminton session for all levels',
    sportType: 'badminton',
    date: '2026-04-04',
    time: '09:00',
    location: 'Kowloon Badminton Centre, Kowloon, Hong Kong',
    latitude: 22.3193,
    longitude: 114.1694,
    skillLevel: 'beginner',
    maxParticipants: 8,
    currentParticipants: 5,
    organizerId: 'user1',
    organizer: mockUsers['user1'],
    status: 'upcoming',
    participants: ['user1', 'user3', 'user4', 'user2', 'user5'],
    waitlist: [],
    coHosts: [],
    createdAt: '2024-04-05',
    updatedAt: '2024-04-05',
  },
  {
    id: 'event6',
    title: 'Running Group',
    description: 'Morning jog around Victoria Park',
    sportType: 'running',
    date: '2026-04-05',
    time: '06:30',
    location: 'Victoria Park, Causeway Bay, Hong Kong',
    latitude: 22.2797,
    longitude: 114.1839,
    skillLevel: 'intermediate',
    maxParticipants: 20,
    currentParticipants: 12,
    organizerId: 'user2',
    organizer: mockUsers['user2'],
    status: 'upcoming',
    participants: ['user2', 'user1', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12'],
    waitlist: [],
    coHosts: ['user3'],
    createdAt: '2024-04-06',
    updatedAt: '2024-04-06',
  },
  {
    id: 'event7',
    title: 'Cricket Match',
    description: 'Friendly cricket match - all welcome',
    sportType: 'cricket',
    date: '2026-04-06',
    time: '15:00',
    location: 'Kowloon Cricket Club, Kowloon, Hong Kong',
    latitude: 22.3193,
    longitude: 114.1694,
    skillLevel: 'intermediate',
    maxParticipants: 22,
    currentParticipants: 18,
    organizerId: 'user3',
    organizer: mockUsers['user3'],
    status: 'upcoming',
    participants: ['user3', 'user1', 'user2', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12', 'user13', 'user14', 'user15', 'user16', 'user17', 'user18'],
    waitlist: [],
    coHosts: ['user2'],
    createdAt: '2024-04-07',
    updatedAt: '2024-04-07',
  },
  {
    id: 'event8',
    title: 'Yoga Session',
    description: 'Relaxing yoga session in the park',
    sportType: 'yoga',
    date: '2026-04-07',
    time: '07:00',
    location: 'Kowloon Park, Kowloon, Hong Kong',
    latitude: 22.3193,
    longitude: 114.1694,
    skillLevel: 'beginner',
    maxParticipants: 15,
    currentParticipants: 10,
    organizerId: 'user4',
    organizer: mockUsers['user4'],
    status: 'upcoming',
    participants: ['user4', 'user1', 'user2', 'user3', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10'],
    waitlist: [],
    coHosts: [],
    createdAt: '2024-04-08',
    updatedAt: '2024-04-08',
  },
  {
    id: 'event9',
    title: 'Cycling Tour',
    description: 'Scenic cycling tour around Hong Kong',
    sportType: 'cycling',
    date: '2026-04-08',
    time: '08:00',
    location: 'Stanley, Hong Kong',
    latitude: 22.2126,
    longitude: 114.2071,
    skillLevel: 'intermediate',
    maxParticipants: 25,
    currentParticipants: 15,
    organizerId: 'user1',
    organizer: mockUsers['user1'],
    status: 'upcoming',
    participants: ['user1', 'user2', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12', 'user13', 'user14', 'user15'],
    waitlist: [],
    coHosts: ['user4'],
    createdAt: '2024-04-09',
    updatedAt: '2024-04-09',
  },
  {
    id: 'event10',
    title: 'Swimming Lessons',
    description: 'Swimming lessons for intermediate swimmers',
    sportType: 'swimming',
    date: '2026-04-09',
    time: '11:00',
    location: 'Hong Kong Swimming Pool, Causeway Bay, Hong Kong',
    latitude: 22.2797,
    longitude: 114.1839,
    skillLevel: 'intermediate',
    maxParticipants: 12,
    currentParticipants: 8,
    organizerId: 'user2',
    organizer: mockUsers['user2'],
    status: 'upcoming',
    participants: ['user2', 'user1', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8'],
    waitlist: [],
    coHosts: [],
    createdAt: '2024-04-10',
    updatedAt: '2024-04-10',
  },
]

// Mock Clubs
export const mockClubs: Club[] = [
  {
    id: 'club1',
    name: 'SF Basketball Club',
    description: 'A community for basketball enthusiasts in San Francisco',
    sport: 'basketball',
    creatorId: 'user1',
    creator: mockUsers['user1'],
    members: ['user1', 'user2', 'user3', 'user4'],
    admins: ['user1'],
    organizers: ['user1'],
    groupChatId: 'chat_club1',
    isPrivate: false,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-01',
    events: [mockEvents[0]],
    membershipRequests: [],
  },
  {
    id: 'club2',
    name: 'Tennis Lovers',
    description: 'For tennis players of all skill levels',
    sport: 'tennis',
    creatorId: 'user3',
    creator: mockUsers['user3'],
    members: ['user3', 'user1', 'user4'],
    admins: ['user3'],
    organizers: ['user3'],
    groupChatId: 'chat_club2',
    isPrivate: false,
    createdAt: '2024-03-05',
    updatedAt: '2024-03-05',
    events: [mockEvents[1]],
    membershipRequests: [],
  },
  {
    id: 'club3',
    name: 'Volleyball Community',
    description: 'Beach and indoor volleyball players',
    sport: 'volleyball',
    creatorId: 'user4',
    creator: mockUsers['user4'],
    members: ['user4', 'user2', 'user1'],
    admins: ['user4'],
    organizers: ['user4'],
    groupChatId: 'chat_club3',
    isPrivate: false,
    createdAt: '2024-03-10',
    updatedAt: '2024-03-10',
    events: [mockEvents[2]],
    membershipRequests: [],
  },
  {
    id: 'club4',
    name: 'Soccer Enthusiasts',
    description: 'Join us for soccer games and training',
    sport: 'soccer',
    creatorId: 'user2',
    creator: mockUsers['user2'],
    members: ['user2', 'user1', 'user3', 'user4'],
    admins: ['user2'],
    organizers: ['user2'],
    groupChatId: 'chat_club4',
    isPrivate: false,
    createdAt: '2024-03-15',
    updatedAt: '2024-03-15',
    events: [mockEvents[3]],
    membershipRequests: [],
  },
  {
    id: 'club5',
    name: 'Badminton Masters',
    description: 'Advanced badminton club for experienced players',
    sport: 'badminton',
    creatorId: 'user1',
    creator: mockUsers['user1'],
    members: ['user1', 'user3', 'user4'],
    admins: ['user1'],
    organizers: ['user1', 'user3'],
    groupChatId: 'chat_club5',
    isPrivate: false,
    createdAt: '2024-03-20',
    updatedAt: '2024-03-20',
    events: [mockEvents[4]],
    membershipRequests: [],
  },
  {
    id: 'club6',
    name: 'Running Enthusiasts',
    description: 'Join our running community for daily jogs',
    sport: 'running',
    creatorId: 'user2',
    creator: mockUsers['user2'],
    members: ['user2', 'user1', 'user3', 'user4'],
    admins: ['user2'],
    organizers: ['user2', 'user3'],
    groupChatId: 'chat_club6',
    isPrivate: false,
    createdAt: '2024-03-22',
    updatedAt: '2024-03-22',
    events: [mockEvents[5]],
    membershipRequests: [],
  },
  {
    id: 'club7',
    name: 'Cricket Club',
    description: 'Cricket enthusiasts and players',
    sport: 'cricket',
    creatorId: 'user3',
    creator: mockUsers['user3'],
    members: ['user3', 'user1', 'user2', 'user4'],
    admins: ['user3'],
    organizers: ['user3', 'user2'],
    groupChatId: 'chat_club7',
    isPrivate: false,
    createdAt: '2024-03-25',
    updatedAt: '2024-03-25',
    events: [mockEvents[6]],
    membershipRequests: [],
  },
  {
    id: 'club8',
    name: 'Yoga & Wellness',
    description: 'Yoga and wellness activities for all levels',
    sport: 'yoga',
    creatorId: 'user4',
    creator: mockUsers['user4'],
    members: ['user4', 'user1', 'user2', 'user3'],
    admins: ['user4'],
    organizers: ['user4'],
    groupChatId: 'chat_club8',
    isPrivate: false,
    createdAt: '2024-03-28',
    updatedAt: '2024-03-28',
    events: [mockEvents[7]],
    membershipRequests: [],
  },
  {
    id: 'club9',
    name: 'Cycling Adventures',
    description: 'Explore Hong Kong on two wheels',
    sport: 'cycling',
    creatorId: 'user1',
    creator: mockUsers['user1'],
    members: ['user1', 'user2', 'user3', 'user4'],
    admins: ['user1'],
    organizers: ['user1', 'user4'],
    groupChatId: 'chat_club9',
    isPrivate: false,
    createdAt: '2024-03-30',
    updatedAt: '2024-03-30',
    events: [mockEvents[8]],
    membershipRequests: [],
  },
  {
    id: 'club10',
    name: 'Swimming Club',
    description: 'Swimming and water sports club',
    sport: 'swimming',
    creatorId: 'user2',
    creator: mockUsers['user2'],
    members: ['user2', 'user1', 'user3', 'user4'],
    admins: ['user2'],
    organizers: ['user2'],
    groupChatId: 'chat_club10',
    isPrivate: false,
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
    events: [mockEvents[9]],
    membershipRequests: [],
  },
]

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: 'msg1',
    chatId: 'chat1',
    senderId: 'user1',
    sender: mockUsers['user1'],
    content: 'Hey! Are you coming to the basketball game tomorrow?',
    createdAt: '2024-04-10T10:00:00Z',
  },
  {
    id: 'msg2',
    chatId: 'chat1',
    senderId: 'user2',
    sender: mockUsers['user2'],
    content: 'Yes! I\'ll be there. What time should I arrive?',
    createdAt: '2024-04-10T10:05:00Z',
  },
  {
    id: 'msg3',
    chatId: 'chat1',
    senderId: 'user1',
    sender: mockUsers['user1'],
    content: 'Around 5 PM would be great!',
    createdAt: '2024-04-10T10:10:00Z',
  },
]

// Mock Chats
export const mockChats: Chat[] = [
  {
    id: 'chat1',
    type: 'direct',
    participants: ['user1', 'user2'],
    messages: mockMessages,
    createdAt: '2024-04-01',
    updatedAt: '2024-04-10',
  },
  {
    id: 'chat2',
    type: 'group',
    name: 'Basketball Team',
    participants: ['user1', 'user2', 'user3', 'user4'],
    messages: [
      {
        id: 'msg4',
        chatId: 'chat2',
        senderId: 'user1',
        sender: mockUsers['user1'],
        content: 'Team meeting tomorrow at 5 PM!',
        createdAt: '2024-04-10T11:00:00Z',
      },
    ],
    createdAt: '2024-04-05',
    updatedAt: '2024-04-10',
  },
]

export default {
  mockUsers,
  mockEvents,
  mockClubs,
  mockMessages,
  mockChats,
}
